#!/usr/bin/env python3
"""QLoRA SFT trainer for ResearchReasoner.

This is a standard Hugging Face/TRL entrypoint. It expects a JSONL file with a
`text` field generated by build_research_sft.py.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict


def load_yaml(path: str) -> Dict[str, Any]:
    import yaml

    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    args = ap.parse_args()
    cfg = load_yaml(args.config)

    import torch
    from datasets import load_dataset
    from peft import LoraConfig
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
    from trl import SFTTrainer

    base_model = cfg.get("base_model") or cfg.get("base_model_or_adapter")
    output_dir = cfg["output_dir"]
    max_seq_length = int(cfg.get("max_seq_length", 8192))

    train_file = cfg["data"]["train_file"]
    eval_file = cfg["data"].get("eval_file")

    data_files = {"train": train_file}
    if eval_file and Path(eval_file).exists():
        data_files["validation"] = eval_file
    ds = load_dataset("json", data_files=data_files)

    tokenizer = AutoTokenizer.from_pretrained(base_model, trust_remote_code=True, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    model = AutoModelForCausalLM.from_pretrained(
        base_model,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
        torch_dtype=torch.bfloat16,
        attn_implementation=os.environ.get("ATTN_IMPL", "sdpa"),
    )
    model.config.use_cache = False

    lora_cfg = cfg["lora"]
    peft_config = LoraConfig(
        r=int(lora_cfg.get("r", 32)),
        lora_alpha=int(lora_cfg.get("alpha", 64)),
        lora_dropout=float(lora_cfg.get("dropout", 0.05)),
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=lora_cfg.get("target_modules"),
    )

    opt = cfg.get("optimizer", {})
    batching = cfg.get("batching", {})
    logging = cfg.get("logging", {})
    training_args = TrainingArguments(
        output_dir=output_dir,
        per_device_train_batch_size=int(batching.get("per_device_train_batch_size", 1)),
        gradient_accumulation_steps=int(batching.get("gradient_accumulation_steps", 16)),
        num_train_epochs=float(batching.get("num_train_epochs", 2)),
        learning_rate=float(opt.get("learning_rate", 2e-5)),
        warmup_ratio=float(opt.get("warmup_ratio", 0.03)),
        weight_decay=float(opt.get("weight_decay", 0.01)),
        lr_scheduler_type=opt.get("lr_scheduler_type", "cosine"),
        optim=opt.get("optim", "paged_adamw_8bit"),
        logging_steps=int(logging.get("logging_steps", 10)),
        save_steps=int(logging.get("save_steps", 500)),
        eval_steps=int(logging.get("eval_steps", 250)),
        evaluation_strategy="steps" if "validation" in ds else "no",
        save_total_limit=2,
        bf16=True,
        gradient_checkpointing=True,
        report_to=logging.get("report_to", "none"),
    )

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=ds["train"],
        eval_dataset=ds.get("validation"),
        dataset_text_field="text",
        max_seq_length=max_seq_length,
        packing=bool(cfg.get("packing", True)),
        peft_config=peft_config,
        args=training_args,
    )
    trainer.train()
    trainer.save_model(output_dir)
    tokenizer.save_pretrained(output_dir)
    with open(Path(output_dir) / "training_config_snapshot.json", "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)


if __name__ == "__main__":
    main()
